spring:
  application:
    name: techefx-spring-cloud-config-server
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/drjeon92/study

server:
  port: ${port:8888}