spring:
  application:
    name: techefx-property-access-service
  
  profiles:
    active:
    - dev
  
  config:
    import:
    - "optional:configserver:"

server:
  port: ${port:8100}
  
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh